server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve1?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 0
    password:
    listen-pattern: __keyevent@0__:expired


missyou:
  security:
    jwt-key: leokkzhang
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify